services:
  - type: web
    name: taskflow-backend
    env: docker
    dockerfilePath: ./Dockerfile
    rootDir: ./backend
    region: singapore
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: SERVER_PORT
        value: 8080
      - key: DB_URL
        value: postgresql://hoangtvse170014:EpDq-Ajv-7URo-5fJ9j6k7U7qE7Cq0C1@ep-rough-cake-a59nsuq.us-east-2.aws.neon.tech/taskflow?sslmode=require
      - key: DB_USERNAME
        value: hoangtvse170014
      - key: DB_PASSWORD
        value: EpDq-Ajv-7URo-5fJ9j6k7U7qE7Cq0C1
      - key: DB_DDL_AUTO
        value: validate
      - key: JWT_SECRET
        value: TaskFlowSecretKey2026VeryLongSecretKeyForJWTSigningMinimum32Bytes!
      - key: ALLOWED_ORIGINS
        value: https://taskflow-frontend-w6lb.onrender.com
      - key: GROQ_API_KEY
        value: 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
      - key: AI_PROVIDER
        value: demo
