package com.taskflow.ai.service;

import com.taskflow.ai.dto.DocumentType;
import com.taskflow.ai.dto.DocumentationRequest;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Builds the system + user prompts sent to the LLM for each documentation
 * type. The instructions are deliberately explicit about the expected
 * Markdown layout so the model produces a stable structure that the frontend
 * can parse.
 */
@Component
public class DocumentationPromptFactory {

    public String buildSystemPrompt(DocumentType type) {
        return """
                You are TaskFlow DocGen, a senior technical writer and Business Analyst.

                You write professional software documentation in valid GitHub-Flavored Markdown.
                You produce ONLY the document body — no preamble, no apology, no closing remarks.
                You never invent people, dates, percentages, or items that are not in the
                provided context. If the context is insufficient, write a clear "[INSUFFICIENT
                DATA]" note in the affected section instead of guessing.

                Style rules:
                - Use a single H1 title at the top.
                - Use H2 / H3 headings only — no deeper levels.
                - Use tables for any tabular data.
                - Use bullet lists for unstructured items.
                - Keep sentences short and concrete.
                - Use bold for emphasis, never all-caps.
                - Output must be valid Markdown that renders cleanly in GitHub, GitLab and VS Code.
                - Do NOT wrap the output in ``` fences.
                """;
    }

    public String buildUserPrompt(DocumentType type, DocumentationRequest request, String context) {
        StringBuilder sb = new StringBuilder();

        sb.append("# Workspace Context\n");
        sb.append("Use the following data pulled from the database as the single source of truth.\n");
        sb.append("If a piece of information is missing, say so explicitly in the document — never fabricate.\n\n");
        sb.append(context);
        sb.append("\n\n");

        sb.append("# Document Specification\n");
        sb.append("Document type: **").append(type.name()).append("**\n");
        if (request.getTopic() != null) sb.append("Topic: ").append(request.getTopic()).append('\n');
        if (request.getProjectId() != null) sb.append("Project ID: ").append(request.getProjectId()).append('\n');
        if (request.getSprintName() != null) sb.append("Sprint: ").append(request.getSprintName()).append('\n');
        if (request.getAudience() != null) sb.append("Audience: ").append(request.getAudience()).append('\n');
        if (request.getAttendees() != null && !request.getAttendees().isEmpty()) {
            sb.append("Attendees: ").append(String.join(", ", request.getAttendees())).append('\n');
        }
        sb.append('\n');

        sb.append("# Output Layout\n");
        sb.append(layoutFor(type));
        sb.append('\n');

        sb.append("# Reminders\n");
        sb.append("- The first line MUST be a `# <title>` heading.\n");
        sb.append("- End the document with a `## Document Metadata` section containing:\n");
        sb.append("  - Generated by: TaskFlow DocGen\n");
        sb.append("  - Date: today's date\n");
        sb.append("- Do NOT include any prose outside the Markdown body.\n");

        return sb.toString();
    }

    private String layoutFor(DocumentType type) {
        return switch (type) {
            case SRS -> """
                    Produce a Software Requirements Specification with these sections:
                    1. Introduction (Purpose, Scope, Definitions)
                    2. Functional Requirements (FR-1, FR-2, … with ID, priority, status, description table)
                    3. Non-Functional Requirements (table of categories and targets)
                    4. Constraints
                    5. Acceptance Criteria (high-level list)
                    6. Document Metadata
                    """;
            case USER_STORIES -> """
                    Produce a User Stories document with these sections:
                    1. Story Index (list of US-1, US-2, … with title)
                    2. Stories — each story contains:
                       - As a / I want / So that
                       - Task ID, Priority, Due
                       - Acceptance Criteria (checkboxes)
                    3. Document Metadata
                    """;
            case ACCEPTANCE_CRITERIA -> """
                    Produce an Acceptance Criteria document with:
                    1. Global Acceptance Criteria (high-level cross-cutting criteria)
                    2. Per-Task Acceptance Criteria — for each task:
                       - AC-{n} heading
                       - Given / When / Then clauses
                       - Linked task key and priority
                    3. Document Metadata
                    """;
            case MEETING_MINUTES -> """
                    Produce Meeting Minutes with:
                    1. Meeting metadata (title, date, facilitator, attendees)
                    2. Attendees (bullet list)
                    3. Agenda
                    4. Discussion Summary (key discussion points with task references)
                    5. Decisions (bullet list)
                    6. Action Items (markdown table — # | Action | Owner | Due)
                    7. Risks
                    8. Next Steps
                    9. Document Metadata
                    """;
            case SPRINT_REVIEW -> """
                    Produce a Sprint Review document with:
                    1. Sprint Goal
                    2. What we planned (task table)
                    3. What we delivered (completed tasks)
                    4. What we did not deliver (pending tasks)
                    5. Metrics (totals, completion %, overdue count)
                    6. Demo references (placeholder)
                    7. Document Metadata
                    """;
            case RETROSPECTIVE -> """
                    Produce a Sprint Retrospective with:
                    1. What went well
                    2. What went poorly
                    3. What to improve (checkboxes)
                    4. Action items for the next sprint (markdown table)
                    5. Team sentiment
                    6. Document Metadata
                    """;
            case TECHNICAL_SPEC -> """
                    Produce a Technical Specification with:
                    1. Overview
                    2. Architecture (textual diagram or bullet list)
                    3. Modules (table — Module | Responsibility | Tech)
                    4. Data Model (entity list with relationships)
                    5. APIs (relevant endpoint list)
                    6. Non-Functional Requirements
                    7. Risks & Mitigations
                    8. Open Questions
                    9. Document Metadata
                    """;
        };
    }

    public List<DocumentType> supportedTypes() {
        return List.of(DocumentType.values());
    }
}
