package com.taskflow.ai.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * A complete, read-only preview of what would be created from a project idea.
 * Generated by chaining AI project planning + AI task assignment.
 *
 * Nothing in this DTO is persisted; the user reviews it and then chooses whether
 * to commit to the database via a separate endpoint (not in scope here).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PreviewProjectResponse {

    /** Stable id of this preview (not stored in DB, generated client/server side). */
    private String previewId;

    /** Plan section (mirrors ProjectPlannerResponse). */
    private ProjectPreview project;

    /** Sprint summary section. */
    private List<SprintSummary> sprints;

    /** Task section with embedded assignment recommendation. */
    private List<TaskPreview> tasks;

    /** Subtasks grouped per parent task for easy rendering. */
    private List<SubtaskPreview> subtasks;

    /** Cross-task execution order computed from the dependency graph. */
    private List<String> executionOrder;

    /** Aggregated estimated duration for the whole plan. */
    private EstimatedDuration estimatedDuration;

    /** Aggregated risk register. */
    private List<RiskItem> risks;

    /** Per-member workload impact summary (from the assignment step). */
    private List<BatchTaskAssignmentResponse.WorkloadSummary> workloadSummary;

    /** Average confidence across all assignment decisions. */
    private Double overallAssignmentConfidence;

    /** Average confidence from the project planning step. */
    private Double planningConfidence;

    /** Combined confidence = average of planning + assignment. */
    private Double overallConfidence;

    /** Warnings raised by either the planner or the assigner. */
    private List<String> warnings;

    /** High-level reasoning. */
    private String reason;

    private Long processingTimeMs;

    private String error;

    // ---------------------------------------------------------------------
    // Nested types
    // ---------------------------------------------------------------------

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ProjectPreview {
        private String name;
        private String description;
        private String scope;
        private Integer weeksDeadline;
        private String technologyStack;
        private String teamSize;
        private Timeline timeline;
        private List<MilestonePreview> milestones;
        private List<EpicPreview> epics;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Timeline {
        private String startDate;
        private String endDate;
        private Integer totalWeeks;
        private Integer totalEstimatedHours;
        private Integer totalStoryPoints;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MilestonePreview {
        private String name;
        private String description;
        private String targetDate;
        private List<String> deliverables;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class EpicPreview {
        private String id;
        private String name;
        private String description;
        private String priority;
        private Integer estimatedHours;
        private List<String> features;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class SprintSummary {
        private Integer number;
        private String name;
        private String goal;
        private String startDate;
        private String endDate;
        private List<String> taskIds;
        private Integer capacity;
        private Integer estimatedHours;
        private Integer taskCount;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TaskPreview {
        private String id;
        private String title;
        private String description;
        private String epicId;
        private String priority;
        private Integer estimatedHours;
        private Integer storyPoints;
        private List<String> acceptanceCriteria;
        private List<String> risks;
        private Integer sprintNumber;
        private String sprintName;
        private AssignmentPreview assignment;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AssignmentPreview {
        private String assignedMemberId;
        private String assignedMemberName;
        private String roleMatched;
        private Double confidence;
        private String reason;
        private Boolean unassigned;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class SubtaskPreview {
        private String id;
        private String parentTaskId;
        private String title;
        private Integer estimatedHours;
        private String suggestedAssignee;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class EstimatedDuration {
        private Integer totalTasks;
        private Integer totalSubtasks;
        private Integer totalEstimatedHours;
        private Integer totalStoryPoints;
        private Integer weeksAtTeamSize;
        private String teamSize;
        private Integer hoursPerWeekPerMember;
        private Integer teamMemberCount;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RiskItem {
        private String level;       // HIGH, MEDIUM, LOW
        private String category;    // SCOPE, TECHNICAL, DEADLINE, RESOURCE, DEPENDENCY
        private String description;
        private String source;      // TASK id or null if aggregated
    }

    public static PreviewProjectResponse error(String message) {
        return PreviewProjectResponse.builder()
                .previewId(null)
                .error(message)
                .build();
    }
}